name: egori.ch
title: C and Sea
markdown: kramdown
theme: minima
github_username: egorich239
linkedin_username: egorich
plugins:
  - jekyll-feed
collections:
  logbook:
    output: true
    permalink: /:collection/:year/:slug:output_ext
  location:
    output: true
    permalink: /:collection/:slug:output_ext
