name: egori.ch
title: C and Sea
markdown: kramdown
theme: minima
github_username: egorich239
linkedin_username: egorich
collections:
  logbook:
    output: true
    permalink: /:collection/:year/:slug:output_ext
  waters:
    output: true
    permalink: /:collection/:slug:output_ext
